"""Write stable build identity without changing an unchanged generated file."""
import argparse
import datetime
import json
import pathlib
import subprocess


def identity(root):
    root = pathlib.Path(root).resolve()
    try:
        # An exported source directory may sit inside another unrelated Git repo.
        top = subprocess.check_output(['git', '-C', str(root), 'rev-parse', '--show-toplevel'], stderr=subprocess.DEVNULL, text=True).strip()
        if pathlib.Path(top).resolve() != root:
            raise ValueError('not the source repository')
        revision = subprocess.check_output(['git', '-C', str(root), 'rev-parse', 'HEAD'], text=True).strip()
        epoch = int(subprocess.check_output(['git', '-C', str(root), 'show', '-s', '--format=%ct', 'HEAD'], text=True))
        dirty = bool(subprocess.check_output(['git', '-C', str(root), 'status', '--porcelain', '--untracked-files=normal'], text=True))
    except (OSError, ValueError, subprocess.CalledProcessError):
        try:
            exported = json.loads((root / 'source-info.json').read_text())
            revision, epoch, dirty = exported['revision'], int(exported['commit_epoch']), bool(exported['dirty'])
        except (OSError, ValueError, KeyError, TypeError):
            revision, epoch, dirty = 'unknown', 0, False
    stamp = datetime.datetime.fromtimestamp(epoch, datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    return {'revision': revision, 'short_revision': revision[:12], 'dirty': dirty,
            'commit_epoch': epoch, 'commit_time': stamp}


def write_if_changed(path, data):
    path = pathlib.Path(path)
    if not path.exists() or path.read_text() != data:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(data)


def generate(root, output):
    info = identity(root)
    label = info['short_revision'] + (' +changes' if info['dirty'] else '')
    header = ('/* Generated by tools/build_info.py; no wall-clock timestamp. */\n'
              '#ifndef BASEOS_BUILD_INFO_H\n#define BASEOS_BUILD_INFO_H\n'
              '#define BASEOS_BUILD_REVISION ' + json.dumps(info['revision']) + '\n'
              '#define BASEOS_BUILD_LABEL ' + json.dumps(label) + '\n'
              '#define BASEOS_BUILD_TIME ' + json.dumps(info['commit_time']) + '\n'
              '#define BASEOS_BUILD_DIRTY ' + str(int(info['dirty'])) + '\n#endif\n')
    write_if_changed(pathlib.Path(output) / 'build_info.h', header)
    write_if_changed(pathlib.Path(output) / 'build_info.json', json.dumps(info, indent=2, sort_keys=True) + '\n')
    return info


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('output', type=pathlib.Path)
    parser.add_argument('--root', type=pathlib.Path, default=pathlib.Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    generate(args.root, args.output)
