#!/usr/bin/env python3
"""Rasterize the UI and editor fonts into 4-bit anti-aliased bitmaps (src/font.h).

Inter (UI, regular + bold) and JetBrains Mono (editor/terminal) are pulled from
the Google Fonts repository into assets/fonts. Both are OFL licensed.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
FONTS = os.path.join(ROOT, "assets", "fonts")
OUT = os.path.join(ROOT, "src", "font.h")
PROOF = os.path.join(ROOT, "screenshots", "font-proof.png")

FIRST = 32
COUNT = 95

UI_SIZE = 14
UI_WEIGHT = 430
UI_BOLD_WEIGHT = 600
EDIT_SIZE = 13
EDIT_WEIGHT = 450
LOGO_SIZE = 34
LOGO_WEIGHT = 720
LOGO_TEXT = "BaseOS0123456789.:-"


def load(path, size, weight, opsz=None):
    font = ImageFont.truetype(path, size)
    axes = font.get_variation_axes()
    vals = []
    for ax in axes:
        name = ax["name"]
        if name == b"Weight":
            vals.append(weight)
        elif name == b"Optical size":
            vals.append(opsz if opsz is not None else ax["default"])
        else:
            vals.append(ax["default"])
    font.set_variation_by_axes(vals)
    return font


def render_glyph(font, ch, cell_h, max_w, mono_adv=None):
    """Return (advance, rows) where rows is a list of lists of levels 0..15."""
    pad = 4
    im = Image.new("L", (max_w + pad * 2, cell_h + pad), 0)
    d = ImageDraw.Draw(im)
    d.text((pad, 0), ch, font=font, fill=255)
    if mono_adv is not None:
        adv = mono_adv
    else:
        adv = int(round(font.getlength(ch)))
    rows = []
    for y in range(cell_h):
        row = []
        for x in range(max_w):
            a = im.getpixel((x + pad, y))
            row.append((a + 8) // 17)
        rows.append(row)
    return adv, rows


def pack_rows(rows, max_w):
    bpr = (max_w + 1) // 2
    out = []
    for row in rows:
        for b in range(bpr):
            v = 0
            for k in range(2):
                x = b * 2 + k
                lvl = row[x] if x < max_w else 0
                v |= lvl << (4 - 4 * k)
            out.append(v)
    return out, bpr


def build(font, cell_h, max_w, mono_adv=None, chars=None):
    glyphs = []
    advs = []
    for i in range(COUNT):
        ch = chr(FIRST + i)
        if chars is not None and ch not in chars:
            continue
        adv, rows = render_glyph(font, ch, cell_h, max_w, mono_adv)
        data, bpr = pack_rows(rows, max_w)
        glyphs.append(data)
        advs.append(adv)
    return advs, glyphs, (max_w + 1) // 2


def emit_array(name, advs, glyphs, bpr, cell_h):
    lines = []
    lines.append(f"static const uint8_t {name}_adv[{len(advs)}] = {{")
    lines.append("    " + ", ".join(str(a) for a in advs))
    lines.append("};")
    lines.append(f"static const uint8_t {name}_px[{len(glyphs)}][{cell_h * bpr}] = {{")
    for g in glyphs:
        body = ", ".join(f"0x{b:02X}" for b in g)
        lines.append("    {" + body + "},")
    lines.append("};")
    return "\n".join(lines)


def main():
    inter = os.path.join(FONTS, "Inter.ttf")
    mono = os.path.join(FONTS, "JetBrainsMono.ttf")
    ui = load(inter, UI_SIZE, UI_WEIGHT, opsz=14)
    uib = load(inter, UI_SIZE, UI_BOLD_WEIGHT, opsz=14)
    ed = load(mono, EDIT_SIZE, EDIT_WEIGHT)
    logo = load(inter, LOGO_SIZE, LOGO_WEIGHT, opsz=32)

    ui_asc, ui_desc = ui.getmetrics()
    ui_h = ui_asc + ui_desc
    ui_w = 16
    ed_asc, ed_desc = ed.getmetrics()
    ed_h = ed_asc + ed_desc
    ed_adv = int(round(ed.getlength("M")))
    ed_w = ed_adv
    lg_asc, lg_desc = logo.getmetrics()
    lg_h = lg_asc + lg_desc
    lg_w = 32

    ui_adv, ui_px, ui_bpr = build(ui, ui_h, ui_w)
    uib_adv, uib_px, _ = build(uib, ui_h, ui_w)
    ed_advs, ed_px, ed_bpr = build(ed, ed_h, ed_w, mono_adv=ed_adv)
    lg_adv, lg_px, lg_bpr = build(logo, lg_h, lg_w, chars=LOGO_TEXT)
    lg_chars = [c for c in (chr(FIRST + i) for i in range(COUNT)) if c in LOGO_TEXT]

    parts = []
    parts.append("#ifndef FONT_H")
    parts.append("#define FONT_H")
    parts.append("")
    parts.append("#include <stdint.h>")
    parts.append("")
    parts.append("/* Generated by tools/gen_font.py. 4 bits per pixel, 2 pixels per byte,")
    parts.append(" * high bits first. Level 0 = transparent, 15 = solid. */")
    parts.append("")
    parts.append(f"#define UI_FONT_H        {ui_h}")
    parts.append(f"#define UI_FONT_ASCENT   {ui_asc}")
    parts.append(f"#define UI_FONT_W        {ui_w}")
    parts.append(f"#define UI_FONT_BPR      {ui_bpr}")
    parts.append(f"#define UI_FONT_FIRST    {FIRST}")
    parts.append(f"#define UI_FONT_COUNT    {COUNT}")
    parts.append(f"#define EDIT_FONT_H      {ed_h}")
    parts.append(f"#define EDIT_FONT_W      {ed_w}")
    parts.append(f"#define EDIT_FONT_BPR    {ed_bpr}")
    parts.append(f"#define EDIT_CHAR_W      {ed_adv}")
    parts.append(f"#define LOGO_FONT_H      {lg_h}")
    parts.append(f"#define LOGO_FONT_W      {lg_w}")
    parts.append(f"#define LOGO_FONT_BPR    {lg_bpr}")
    parts.append(f"#define LOGO_FONT_COUNT  {len(lg_chars)}")
    parts.append("")
    parts.append(emit_array("ui_font", ui_adv, ui_px, ui_bpr, ui_h))
    parts.append("")
    parts.append(emit_array("uib_font", uib_adv, uib_px, ui_bpr, ui_h))
    parts.append("")
    parts.append(emit_array("edit_font", ed_advs, ed_px, ed_bpr, ed_h))
    parts.append("")
    parts.append("static const char logo_font_chars[] = \"" + "".join(lg_chars) + "\";")
    parts.append(emit_array("logo_font", lg_adv, lg_px, lg_bpr, lg_h))
    parts.append("")
    parts.append("#endif")
    src = "\n".join(parts) + "\n"
    with open(OUT, "w") as f:
        f.write(src)
    print("wrote", OUT, len(src), "bytes")
    print("ui", ui_h, "x", ui_w, "edit", ed_h, "x", ed_w, "adv", ed_adv, "logo", lg_h)

    proof(ui_adv, ui_px, ui_bpr, ui_h, ui_w, uib_adv, uib_px, ed_advs, ed_px, ed_bpr, ed_h, ed_w)


def blit(im, x, y, data, bpr, h, w, scale):
    px = im.load()
    for row in range(h):
        for col in range(w):
            b = data[row * bpr + col // 2]
            lvl = (b >> (4 - 4 * (col % 2))) & 15
            if lvl == 0:
                continue
            v = 255 - lvl * 17
            for sy in range(scale):
                for sx in range(scale):
                    px[(x + col) * scale + sx, (y + row) * scale + sy] = (v, v, v)


def proof(ui_adv, ui_px, ui_bpr, ui_h, ui_w, uib_adv, uib_px, ed_adv, ed_px, ed_bpr, ed_h, ed_w):
    lines = [
        ("ui", "The quick brown fox jumps over the lazy dog 0123456789"),
        ("uib", "Files Editor Calculator Paint Viewer Snake Wordle Terminal"),
        ("ui", "BaseOS File Edit System  Wordle Hello World  15:42"),
        ("ed", "int main(void) { return 0; } /* editor mono */"),
    ]
    scale = 2
    W, H = 520, 20 + len(lines) * 24
    im = Image.new("RGB", (W * scale, H * scale), (255, 255, 255))
    y = 8
    for kind, text in lines:
        x = 8
        for ch in text:
            i = ord(ch) - FIRST
            if kind == "ui":
                blit(im, x, y, ui_px[i], ui_bpr, ui_h, ui_w, scale)
                x += ui_adv[i]
            elif kind == "uib":
                blit(im, x, y, uib_px[i], ui_bpr, ui_h, ui_w, scale)
                x += uib_adv[i]
            else:
                blit(im, x, y, ed_px[i], ed_bpr, ed_h, ed_w, scale)
                x += ed_adv[i]
        y += 24
    os.makedirs(os.path.dirname(PROOF), exist_ok=True)
    im.save(PROOF)
    print("proof", PROOF)


if __name__ == "__main__":
    main()
